/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Patient;
import model.PatientHistory;

/**
 *
 * @author parjita
 */
public class CreatePatientJForm extends javax.swing.JPanel {

    PatientHistory history;

    /**
     * Creates new form CreatePatientJForm
     * @param history
     */
    public CreatePatientJForm(PatientHistory history) {
        initComponents();
        this.history = history;
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientSaveBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PatientIdText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PatientNameText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PatientAgeText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PatientGenderText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PatientAddressText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PatientEmailIDText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        PatientPhoneNumberText = new javax.swing.JTextField();
        PatientSavebtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PatientWeightText = new javax.swing.JTextField();
        PatientHeightText = new javax.swing.JTextField();

        PatientSaveBtn.setText("Save");
        PatientSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientSaveBtnActionPerformed(evt);
            }
        });

        setPreferredSize(new java.awt.Dimension(578, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Detail");

        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("Patient ID");
        jLabel2.setToolTipText("");

        PatientIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientIdTextActionPerformed(evt);
            }
        });
        PatientIdText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PatientIdTextKeyReleased(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("Name");

        PatientNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientNameTextActionPerformed(evt);
            }
        });
        PatientNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PatientNameTextKeyReleased(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 0, 255));
        jLabel5.setText("Age");

        PatientAgeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientAgeTextActionPerformed(evt);
            }
        });
        PatientAgeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PatientAgeTextKeyReleased(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 0, 255));
        jLabel6.setText("Gender");

        PatientGenderText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientGenderTextActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(204, 0, 204));
        jLabel8.setText("Address");

        PatientAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientAddressTextActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 0, 255));
        jLabel10.setText("Email ID");

        PatientEmailIDText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PatientEmailIDTextKeyReleased(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 0, 255));
        jLabel11.setText("Phone Number");

        PatientPhoneNumberText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PatientPhoneNumberTextKeyReleased(evt);
            }
        });

        PatientSavebtn.setBackground(new java.awt.Color(255, 0, 255));
        PatientSavebtn.setForeground(new java.awt.Color(255, 255, 255));
        PatientSavebtn.setText("Save");
        PatientSavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientSavebtnActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 0, 255));
        jLabel12.setText("Weight");

        jLabel13.setForeground(new java.awt.Color(255, 0, 255));
        jLabel13.setText("Height");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(223, 223, 223))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PatientPhoneNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PatientAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PatientEmailIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PatientSavebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(222, 222, 222))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PatientAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PatientNameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PatientIdText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(223, 223, 223))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(PatientHeightText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addComponent(PatientWeightText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PatientGenderText, javax.swing.GroupLayout.Alignment.LEADING))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PatientGenderText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientWeightText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientHeightText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientPhoneNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientEmailIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PatientSavebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PatientNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientNameTextActionPerformed

    private void PatientSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientSaveBtnActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_PatientSaveBtnActionPerformed

    private void PatientGenderTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientGenderTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientGenderTextActionPerformed

    private void PatientAgeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientAgeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientAgeTextActionPerformed

    private void PatientAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientAddressTextActionPerformed

    private void PatientSavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientSavebtnActionPerformed
        // TODO add your handling code here:
        int PatientID  =  Integer.parseInt(PatientIdText.getText());
        String PatientName = PatientNameText.getText();
        String PatientDOB = PatientAgeText.getText();
        String PatientGender = PatientGenderText.getText();
        int PatientAge = Integer.parseInt(PatientAgeText.getText()); 
        int PatientWeight = Integer.parseInt(PatientWeightText.getText());
        int PatientHeight = Integer.parseInt(PatientHeightText.getText());
        String PatientAddress = PatientAddressText.getText();
        String PatientEmailID = PatientEmailIDText.getText();
        Double PatientPhoneNumber = Double.parseDouble(PatientPhoneNumberText.getText());
        

        Patient h = history.addNewPatient();
        h.setPatientID(PatientID);
        h.setPatientName(PatientName);
        h.setPatientGender(PatientGender);
        h.setPatientWeight(PatientWeight);
        h.setPatientAge(PatientAge);
        h.setPatientHeight(PatientHeight);       
        h.setPatientAddress(PatientAddress);     
        h.setPatientEmail(PatientEmailID);
        h.setPatientPhoneNumber(PatientPhoneNumber);

        JOptionPane.showMessageDialog(this,"New Patient Detail Added.");

        PatientIdText.setText("");
        PatientNameText.setText("");
        PatientAgeText.setText("");
        PatientWeightText.setText("");
        PatientHeightText.setText("");
        PatientGenderText.setText("");
        PatientAddressText.setText("");
        PatientEmailIDText.setText("");
        PatientPhoneNumberText.setText("");              
        
    }//GEN-LAST:event_PatientSavebtnActionPerformed

    private void PatientIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientIdTextActionPerformed

    private void PatientIdTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PatientIdTextKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(PatientIdText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid ID ");
        }
    }//GEN-LAST:event_PatientIdTextKeyReleased

    private void PatientNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PatientNameTextKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,40}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(PatientNameText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Name ");
        }
    }//GEN-LAST:event_PatientNameTextKeyReleased

    private void PatientAgeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PatientAgeTextKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,2}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(PatientAgeText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Value ");
        }
    }//GEN-LAST:event_PatientAgeTextKeyReleased

    private void PatientPhoneNumberTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PatientPhoneNumberTextKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,9}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(PatientPhoneNumberText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Value ");
        }
    }//GEN-LAST:event_PatientPhoneNumberTextKeyReleased

    private void PatientEmailIDTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PatientEmailIDTextKeyReleased
        // TODO add your handling code here:
       String PATTERN = "^[a-zA-Z0-9(.+)@(\\\\S+)]{0,40}$";
       Pattern patt = Pattern.compile(PATTERN);
       Matcher match = patt.matcher(PatientEmailIDText.getText());

       if(!match.matches()){            
           JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid EmailAdress ");
       }
    }//GEN-LAST:event_PatientEmailIDTextKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PatientAddressText;
    private javax.swing.JTextField PatientAgeText;
    private javax.swing.JTextField PatientEmailIDText;
    private javax.swing.JTextField PatientGenderText;
    private javax.swing.JTextField PatientHeightText;
    private javax.swing.JTextField PatientIdText;
    private javax.swing.JTextField PatientNameText;
    private javax.swing.JTextField PatientPhoneNumberText;
    private javax.swing.JButton PatientSaveBtn;
    private javax.swing.JButton PatientSavebtn;
    private javax.swing.JTextField PatientWeightText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
