/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Doctor;
import model.DoctorHistory;

/**
 *
 * @author parjita
 */
public class CreateDoctorJForm extends javax.swing.JPanel {

      DoctorHistory history;
    /**
     * Creates new form CreateDoctorJForm
     * @param history
     */
    public CreateDoctorJForm(DoctorHistory history) {
        initComponents();
          this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DoctorIdText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DoctorNameText = new javax.swing.JTextField();
        DoctorSaveBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        HospitalIDText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DoctorContactNumberText = new javax.swing.JTextField();
        DoctorEmailIDText = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Doctor Detail");

        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("Doctor ID");

        DoctorIdText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DoctorIdTextKeyReleased(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("Doctor Name");

        DoctorNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorNameTextActionPerformed(evt);
            }
        });
        DoctorNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DoctorNameTextKeyReleased(evt);
            }
        });

        DoctorSaveBtn.setBackground(new java.awt.Color(255, 0, 255));
        DoctorSaveBtn.setForeground(new java.awt.Color(255, 255, 255));
        DoctorSaveBtn.setText("Save");
        DoctorSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorSaveBtnActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 0, 255));
        jLabel4.setText("Hospital ID");

        HospitalIDText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                HospitalIDTextKeyReleased(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 0, 255));
        jLabel5.setText("Contact Number");

        jLabel6.setForeground(new java.awt.Color(255, 0, 255));
        jLabel6.setText("Email ID");

        DoctorContactNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorContactNumberTextActionPerformed(evt);
            }
        });
        DoctorContactNumberText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DoctorContactNumberTextKeyReleased(evt);
            }
        });

        DoctorEmailIDText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DoctorEmailIDTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DoctorIdText, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(DoctorNameText)
                            .addComponent(HospitalIDText)
                            .addComponent(DoctorContactNumberText)
                            .addComponent(DoctorEmailIDText)
                            .addComponent(DoctorSaveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HospitalIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorContactNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorEmailIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(DoctorSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DoctorNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorNameTextActionPerformed

    private void DoctorSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorSaveBtnActionPerformed
        // TODO add your handling code here:
        int DoctorID  =  Integer.parseInt(DoctorIdText.getText());
        String DoctorName = DoctorNameText.getText();
        int HospitalID  =  Integer.parseInt(HospitalIDText.getText());
        Double DoctorContactNumber = Double.parseDouble(DoctorContactNumberText.getText());
        String DoctorEmailId = DoctorEmailIDText.getText();

        Doctor D = history.addNewDoctor();
        D.setDoctorID(DoctorID);
        D.setDoctorName(DoctorName);
        D.setHospitalID(HospitalID);
        D.setDoctorContactNumber(DoctorContactNumber);
        D.setDoctorEmailAddress(DoctorEmailId);

        JOptionPane.showMessageDialog(this,"New Doctor Detail Added.");

        DoctorIdText.setText("");
        DoctorNameText.setText("");
        HospitalIDText.setText("");
        DoctorContactNumberText.setText("");
        DoctorEmailIDText.setText("");
        
    }//GEN-LAST:event_DoctorSaveBtnActionPerformed

    private void DoctorContactNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorContactNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorContactNumberTextActionPerformed

    private void DoctorIdTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DoctorIdTextKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(DoctorIdText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid ID ");
        }
    }//GEN-LAST:event_DoctorIdTextKeyReleased

    private void DoctorNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DoctorNameTextKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,40}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(DoctorNameText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Name ");
        }
    }//GEN-LAST:event_DoctorNameTextKeyReleased

    private void HospitalIDTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HospitalIDTextKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(HospitalIDText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid ID ");
        }
    }//GEN-LAST:event_HospitalIDTextKeyReleased

    private void DoctorContactNumberTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DoctorContactNumberTextKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,10}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(DoctorContactNumberText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid PhoneNumber ");
        }
    }//GEN-LAST:event_DoctorContactNumberTextKeyReleased

    private void DoctorEmailIDTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DoctorEmailIDTextKeyReleased
        // TODO add your handling code here:
       String PATTERN = "^[a-zA-Z0-9(.+)@(\\\\S+)]{0,40}$";
       Pattern patt = Pattern.compile(PATTERN);
       Matcher match = patt.matcher(DoctorEmailIDText.getText());

       if(!match.matches()){            
           JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid EmailAdress ");
       }
    }//GEN-LAST:event_DoctorEmailIDTextKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DoctorContactNumberText;
    private javax.swing.JTextField DoctorEmailIDText;
    private javax.swing.JTextField DoctorIdText;
    private javax.swing.JTextField DoctorNameText;
    private javax.swing.JButton DoctorSaveBtn;
    private javax.swing.JTextField HospitalIDText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
