/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Community;
import model.CommunityHistory;

/**
 *
 * @author parjita
 */
public class CreateCommunityJForm extends javax.swing.JPanel {

    CommunityHistory history;
    /**
     * Creates new form CreateCommintyJForm
     * @param history
     */
    public CreateCommunityJForm(CommunityHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CommunityIdText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CommunityNameText = new javax.swing.JTextField();
        CommunitySaveBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CommunityCityText = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Community Detail");

        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("Community ID");

        CommunityIdText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CommunityIdTextKeyReleased(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("Community Name");

        CommunityNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunityNameTextActionPerformed(evt);
            }
        });
        CommunityNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CommunityNameTextKeyReleased(evt);
            }
        });

        CommunitySaveBtn.setBackground(new java.awt.Color(255, 0, 255));
        CommunitySaveBtn.setForeground(new java.awt.Color(255, 255, 255));
        CommunitySaveBtn.setText("Save");
        CommunitySaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunitySaveBtnActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 51, 255));
        jLabel4.setText("City");

        CommunityCityText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CommunityCityTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CommunityIdText, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(CommunityNameText)
                            .addComponent(CommunityCityText)
                            .addComponent(CommunitySaveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CommunityIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CommunityNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CommunityCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(CommunitySaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CommunityNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunityNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommunityNameTextActionPerformed

    private void CommunitySaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunitySaveBtnActionPerformed
        // TODO add your handling code here:
        int CommunityID  =  Integer.parseInt(CommunityIdText.getText());
        String CommunityName = CommunityNameText.getText();
        String CommunityCity = CommunityCityText.getText();

        Community h = history.addNewCommunity();
        h.setCommunityID(CommunityID);
        h.setCommunityName(CommunityName);
        h.setCommunityCity(CommunityCity);

        JOptionPane.showMessageDialog(this,"New Community Detail Added.");

        CommunityIdText.setText("");
        CommunityNameText.setText("");
        CommunityCityText.setText("");
    }//GEN-LAST:event_CommunitySaveBtnActionPerformed

    private void CommunityIdTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CommunityIdTextKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(CommunityIdText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid ID ");
        }
    }//GEN-LAST:event_CommunityIdTextKeyReleased

    private void CommunityNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CommunityNameTextKeyReleased
        // TODO add your handling code here:
            String PATTERN = "^[a-zA-Z]{0,40}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(CommunityNameText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Name ");
        }
    }//GEN-LAST:event_CommunityNameTextKeyReleased

    private void CommunityCityTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CommunityCityTextKeyReleased
        String PATTERN = "^[a-zA-Z]{0,40}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(CommunityCityText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Value ");
            // TODO add your handling code here:
        }
    }//GEN-LAST:event_CommunityCityTextKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CommunityCityText;
    private javax.swing.JTextField CommunityIdText;
    private javax.swing.JTextField CommunityNameText;
    private javax.swing.JButton CommunitySaveBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
