/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Hospital;
import model.HospitalHistory;

/**
 *
 * @author parjita
 */
public class CreateHospitalJForm extends javax.swing.JPanel {
    
    HospitalHistory history;

    /**
     * Creates new form HospitalForm
     * @param history
     */
    public CreateHospitalJForm(HospitalHistory history) {        
        initComponents();
        this.history = history;
    }

   
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HospitalIdText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        HospitalNameText = new javax.swing.JTextField();
        HospitalSaveBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        HospitalCityText = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospital Detail");

        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("Hospital ID");

        HospitalIdText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                HospitalIdTextKeyReleased(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 51, 255));
        jLabel3.setText("Hospital Name");

        HospitalNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalNameTextActionPerformed(evt);
            }
        });
        HospitalNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                HospitalNameTextKeyReleased(evt);
            }
        });

        HospitalSaveBtn.setBackground(new java.awt.Color(255, 0, 255));
        HospitalSaveBtn.setForeground(new java.awt.Color(255, 255, 255));
        HospitalSaveBtn.setText("Save");
        HospitalSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalSaveBtnActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 51, 255));
        jLabel4.setText("City");

        HospitalCityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalCityTextActionPerformed(evt);
            }
        });
        HospitalCityText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                HospitalCityTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HospitalIdText, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(HospitalNameText)
                            .addComponent(HospitalCityText)
                            .addComponent(HospitalSaveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HospitalIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HospitalNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HospitalCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(HospitalSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HospitalSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalSaveBtnActionPerformed
        // TODO add your handling code here:
           int HospitalID  =  Integer.parseInt(HospitalIdText.getText());
           String HospitalName = HospitalNameText.getText();
           String HospitalCity = HospitalCityText.getText();
           
            Hospital h = history.addNewHospital();
               h.setHospitalID(HospitalID);
               h.setHospitalName(HospitalName);
               h.setHospitalCity(HospitalCity);
               
               JOptionPane.showMessageDialog(this,"New Hospital Detail Added.");
               
               HospitalIdText.setText("");
               HospitalNameText.setText("");
               HospitalCityText.setText("");
    }//GEN-LAST:event_HospitalSaveBtnActionPerformed

    private void HospitalNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalNameTextActionPerformed

    private void HospitalIdTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HospitalIdTextKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(HospitalIdText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid ID ");
        }
    }//GEN-LAST:event_HospitalIdTextKeyReleased

    private void HospitalNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HospitalNameTextKeyReleased
        // TODO add your handling code here:
         String PATTERN = "^[a-zA-Z]{0,40}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(HospitalNameText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Name ");
        }
    }//GEN-LAST:event_HospitalNameTextKeyReleased

    private void HospitalCityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalCityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalCityTextActionPerformed

    private void HospitalCityTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HospitalCityTextKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,40}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(HospitalCityText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Value ");
        }
    }//GEN-LAST:event_HospitalCityTextKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HospitalCityText;
    private javax.swing.JTextField HospitalIdText;
    private javax.swing.JTextField HospitalNameText;
    private javax.swing.JButton HospitalSaveBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
