/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.JFrame;
import model.CommunityHistory;
import model.DoctorHistory;
import model.HospitalHistory;
import model.PatientHistory;

/**
 *
 * @author parjita
 */
public class DoctorFrame extends javax.swing.JFrame {

    DoctorHistory doctorHistory;
    HospitalHistory hospitalHistory;
    PatientHistory patientHistory;
    CommunityHistory communityHistory;
    /**
     * Creates new form DoctorFrame
     * @param doctorHistory
     * @param hospitalHistory
     * @param communityHistory
     * @param patientHistory
     */
    public DoctorFrame(DoctorHistory doctorHistory,HospitalHistory hospitalHistory,PatientHistory patientHistory,CommunityHistory communityHistory) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.patientHistory = patientHistory;
        this.doctorHistory = doctorHistory;
        this.hospitalHistory = hospitalHistory;
        this.communityHistory = communityHistory;
    }

    public DoctorFrame() {
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        CommunityLeftPanel = new javax.swing.JPanel();
        CreateCommunityList = new javax.swing.JButton();
        ViewCommunityList = new javax.swing.JButton();
        DoctorUpdateBtn = new javax.swing.JButton();
        BavkBtn = new javax.swing.JButton();
        CommunityRightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CommunityLeftPanel.setPreferredSize(new java.awt.Dimension(32767, 32767));

        CreateCommunityList.setBackground(new java.awt.Color(255, 0, 255));
        CreateCommunityList.setForeground(new java.awt.Color(255, 255, 255));
        CreateCommunityList.setText("Create");
        CreateCommunityList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateCommunityListActionPerformed(evt);
            }
        });

        ViewCommunityList.setBackground(new java.awt.Color(255, 0, 255));
        ViewCommunityList.setForeground(new java.awt.Color(255, 255, 255));
        ViewCommunityList.setText("View");
        ViewCommunityList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCommunityListActionPerformed(evt);
            }
        });

        DoctorUpdateBtn.setBackground(new java.awt.Color(255, 0, 255));
        DoctorUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        DoctorUpdateBtn.setText("Update");
        DoctorUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorUpdateBtnActionPerformed(evt);
            }
        });

        BavkBtn.setBackground(new java.awt.Color(255, 0, 255));
        BavkBtn.setForeground(new java.awt.Color(255, 255, 255));
        BavkBtn.setText("Back");
        BavkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BavkBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CommunityLeftPanelLayout = new javax.swing.GroupLayout(CommunityLeftPanel);
        CommunityLeftPanel.setLayout(CommunityLeftPanelLayout);
        CommunityLeftPanelLayout.setHorizontalGroup(
            CommunityLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommunityLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CommunityLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BavkBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateCommunityList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewCommunityList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(DoctorUpdateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CommunityLeftPanelLayout.setVerticalGroup(
            CommunityLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommunityLeftPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(CreateCommunityList, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ViewCommunityList, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(DoctorUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(BavkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(CommunityLeftPanel);

        CommunityRightPanel.setPreferredSize(new java.awt.Dimension(32767, 32767));

        javax.swing.GroupLayout CommunityRightPanelLayout = new javax.swing.GroupLayout(CommunityRightPanel);
        CommunityRightPanel.setLayout(CommunityRightPanelLayout);
        CommunityRightPanelLayout.setHorizontalGroup(
            CommunityRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
        );
        CommunityRightPanelLayout.setVerticalGroup(
            CommunityRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(CommunityRightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateCommunityListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateCommunityListActionPerformed

        // TODO add your handling code here:
        CreateDoctorJForm CreatePanel = new CreateDoctorJForm(doctorHistory);
        jSplitPane1.setRightComponent(CreatePanel);
    }//GEN-LAST:event_CreateCommunityListActionPerformed

    private void ViewCommunityListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCommunityListActionPerformed
        // TODO add your handling code here:
        ViewDoctorJList ViewPanel = new ViewDoctorJList(doctorHistory);
        jSplitPane1.setRightComponent(ViewPanel);
    }//GEN-LAST:event_ViewCommunityListActionPerformed

    private void DoctorUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorUpdateBtnActionPerformed
        // TODO add your handling code here:
        UpdateDoctorJList ViewPanel = new UpdateDoctorJList(doctorHistory);
        jSplitPane1.setRightComponent(ViewPanel);        
    }//GEN-LAST:event_DoctorUpdateBtnActionPerformed

    private void BavkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BavkBtnActionPerformed
        // TODO add your handling code here:
       
        SystemAdmin frame = new SystemAdmin(hospitalHistory,doctorHistory,patientHistory,communityHistory);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_BavkBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BavkBtn;
    private javax.swing.JPanel CommunityLeftPanel;
    private javax.swing.JPanel CommunityRightPanel;
    private javax.swing.JButton CreateCommunityList;
    private javax.swing.JButton DoctorUpdateBtn;
    private javax.swing.JButton ViewCommunityList;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
