/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.JFrame;
import model.CommunityHistory;
import model.DoctorHistory;
import model.HospitalHistory;
import model.PatientHistory;

/**
 *
 * @author parjita
 */
public class HospitalFrame extends javax.swing.JFrame {

    /**
     * Creates new form Hospital
     */
    
    HospitalHistory hospitalHistory;
    DoctorHistory doctorHistory;
    PatientHistory patientHistory;
    CommunityHistory communityHistory;
    public HospitalFrame(HospitalHistory hospitalHistory,DoctorHistory doctorHistory,PatientHistory patientHistory,CommunityHistory communityHistory) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.hospitalHistory = hospitalHistory;
        this.doctorHistory = doctorHistory;
        this.patientHistory = patientHistory;
        this.communityHistory = communityHistory;
    }

    public HospitalFrame() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        HospitalLeftPanel = new javax.swing.JPanel();
        CreateHospitalList = new javax.swing.JButton();
        ViewHospitalList = new javax.swing.JButton();
        HospitalUpdateBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        HospitalRightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreateHospitalList.setBackground(new java.awt.Color(255, 0, 255));
        CreateHospitalList.setForeground(new java.awt.Color(255, 255, 255));
        CreateHospitalList.setText("Create");
        CreateHospitalList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateHospitalListActionPerformed(evt);
            }
        });

        ViewHospitalList.setBackground(new java.awt.Color(255, 0, 255));
        ViewHospitalList.setForeground(new java.awt.Color(255, 255, 255));
        ViewHospitalList.setText("View");
        ViewHospitalList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewHospitalListActionPerformed(evt);
            }
        });

        HospitalUpdateBtn.setBackground(new java.awt.Color(255, 0, 255));
        HospitalUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        HospitalUpdateBtn.setText("Update");
        HospitalUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalUpdateBtnActionPerformed(evt);
            }
        });

        BackBtn.setBackground(new java.awt.Color(255, 0, 255));
        BackBtn.setForeground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HospitalLeftPanelLayout = new javax.swing.GroupLayout(HospitalLeftPanel);
        HospitalLeftPanel.setLayout(HospitalLeftPanelLayout);
        HospitalLeftPanelLayout.setHorizontalGroup(
            HospitalLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HospitalLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HospitalLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(HospitalUpdateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(CreateHospitalList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewHospitalList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HospitalLeftPanelLayout.setVerticalGroup(
            HospitalLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HospitalLeftPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(CreateHospitalList, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ViewHospitalList, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HospitalUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(HospitalLeftPanel);

        javax.swing.GroupLayout HospitalRightPanelLayout = new javax.swing.GroupLayout(HospitalRightPanel);
        HospitalRightPanel.setLayout(HospitalRightPanelLayout);
        HospitalRightPanelLayout.setHorizontalGroup(
            HospitalRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        HospitalRightPanelLayout.setVerticalGroup(
            HospitalRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(HospitalRightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSplitPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateHospitalListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateHospitalListActionPerformed
        
        // TODO add your handling code here:
        CreateHospitalJForm CreatePanel = new CreateHospitalJForm(hospitalHistory);
        jSplitPane2.setRightComponent(CreatePanel);
    }//GEN-LAST:event_CreateHospitalListActionPerformed

    private void ViewHospitalListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewHospitalListActionPerformed
        // TODO add your handling code here:
        ViewHospitalJList ViewPanel = new ViewHospitalJList(hospitalHistory);
        jSplitPane2.setRightComponent(ViewPanel);
    }//GEN-LAST:event_ViewHospitalListActionPerformed

    private void HospitalUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalUpdateBtnActionPerformed
        // TODO add your handling code here:
        UpdateHospitalJList UpdatePanel = new UpdateHospitalJList(hospitalHistory);
        jSplitPane2.setRightComponent(UpdatePanel);
    }//GEN-LAST:event_HospitalUpdateBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
       
        // TODO add your handling code here:
       
        SystemAdmin frame = new SystemAdmin(hospitalHistory,doctorHistory,patientHistory,communityHistory);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton CreateHospitalList;
    private javax.swing.JPanel HospitalLeftPanel;
    private javax.swing.JPanel HospitalRightPanel;
    private javax.swing.JButton HospitalUpdateBtn;
    private javax.swing.JButton ViewHospitalList;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables

    
}
