/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.JFrame;
import model.CommunityHistory;
import model.DoctorHistory;
import model.HospitalHistory;
import model.PatientHistory;

/**
 *
 * @author parjita
 */
public class SystemAdmin extends javax.swing.JFrame {

    HospitalHistory hospitalHistory;
    DoctorHistory doctorHistory;
    PatientHistory patientHistory;
    CommunityHistory communityHistory;

    /**
     * Creates new form SystemAdmin
     *
     * @param hospitalHistory
     * @param doctorHistory
     * @param patientHistory
     * @param communityHistory
     */
    public SystemAdmin(HospitalHistory hospitalHistory, DoctorHistory doctorHistory,PatientHistory patientHistory,CommunityHistory communityHistory) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.hospitalHistory = hospitalHistory;
        this.doctorHistory = doctorHistory;
        this.patientHistory = patientHistory;
        this.communityHistory = communityHistory;
    }

    public SystemAdmin() {

    } 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DoctorPanelbtn = new javax.swing.JButton();
        PatientDetailbtn = new javax.swing.JButton();
        HospitalDetailbtn = new javax.swing.JButton();
        Logoutbtn = new javax.swing.JButton();
        Communitybtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        DoctorPanelbtn.setText("Doctor Panel");
        DoctorPanelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorPanelbtnActionPerformed(evt);
            }
        });

        PatientDetailbtn.setText("Patient Detail");
        PatientDetailbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientDetailbtnActionPerformed(evt);
            }
        });

        HospitalDetailbtn.setText("Hospitals Detail");
        HospitalDetailbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalDetailbtnActionPerformed(evt);
            }
        });

        Logoutbtn.setBackground(new java.awt.Color(255, 0, 255));
        Logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        Logoutbtn.setText("LogOut");
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });

        Communitybtn.setText("Community Detail");
        Communitybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunitybtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PatientDetailbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(HospitalDetailbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Communitybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DoctorPanelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Communitybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HospitalDetailbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DoctorPanelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(PatientDetailbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoctorPanelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorPanelbtnActionPerformed
        // TODO add your handling code here:
       
        DoctorFrame frame = new DoctorFrame(doctorHistory,hospitalHistory,patientHistory,communityHistory);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_DoctorPanelbtnActionPerformed
    
    private void HospitalDetailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalDetailbtnActionPerformed
        // TODO add your handling code here:
       
        HospitalFrame frame = new HospitalFrame(hospitalHistory,doctorHistory,patientHistory,communityHistory);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_HospitalDetailbtnActionPerformed

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
        // TODO add your handling code here:

        Login frame = new Login();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutbtnActionPerformed

    private void CommunitybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunitybtnActionPerformed
        // TODO add your handling code here:

        CommunityFrame frame = new CommunityFrame(communityHistory,hospitalHistory,doctorHistory,patientHistory);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_CommunitybtnActionPerformed

    private void PatientDetailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientDetailbtnActionPerformed
        // TODO add your handling code here:

        PatientFrame frame = new PatientFrame(patientHistory,hospitalHistory,doctorHistory,communityHistory);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_PatientDetailbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Communitybtn;
    private javax.swing.JButton DoctorPanelbtn;
    private javax.swing.JButton HospitalDetailbtn;
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JButton PatientDetailbtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
