package UI;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Community;
import model.CommunityHistory;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author parjita
 */
public class UpdateCommunityJList extends javax.swing.JPanel {

    CommunityHistory history;
    /**
     * Creates new form UpdateCommunityList
     * @param history
     */
    public UpdateCommunityJList(CommunityHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CommunityIDText = new javax.swing.JTextField();
        CommunitySearchBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CommunityNameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CommunityCityText = new javax.swing.JTextField();
        CommunityUpdateBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search and Update Community List");

        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("Community ID");

        CommunityIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunityIDTextActionPerformed(evt);
            }
        });
        CommunityIDText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CommunityIDTextKeyReleased(evt);
            }
        });

        CommunitySearchBtn.setBackground(new java.awt.Color(255, 0, 255));
        CommunitySearchBtn.setForeground(new java.awt.Color(255, 255, 255));
        CommunitySearchBtn.setText("Search");
        CommunitySearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunitySearchBtnActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("Community Name");

        CommunityNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CommunityNameTextKeyReleased(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 0, 255));
        jLabel4.setText("City");

        CommunityCityText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CommunityCityTextKeyReleased(evt);
            }
        });

        CommunityUpdateBtn.setBackground(new java.awt.Color(255, 0, 255));
        CommunityUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        CommunityUpdateBtn.setText("Update");
        CommunityUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunityUpdateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CommunitySearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CommunityIDText)
                                .addComponent(CommunityNameText)
                                .addComponent(CommunityCityText, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)))
                        .addComponent(CommunityUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CommunityIDText, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(CommunitySearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CommunityNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CommunityCityText, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(CommunityUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CommunityIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunityIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommunityIDTextActionPerformed

    private void CommunitySearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunitySearchBtnActionPerformed
        // TODO add your handling code here:
       int communityID = Integer.parseInt(CommunityIDText.getText());
       
       for (Community C : history.getHistory()) {
        if (communityID == C.getCommunityID()) {
                CommunityNameText.setText(C.getCommunityName());
                CommunityCityText.setText(C.getCommunityCity());
            }
       }
    
    }//GEN-LAST:event_CommunitySearchBtnActionPerformed

    private void CommunityUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunityUpdateBtnActionPerformed
        // TODO add your handling code here:
        for (Community C : history.getHistory()){
         
            if(CommunityIDText.getText().equals(String.valueOf(C.getCommunityID()))) {
                
                C.setCommunityName(CommunityNameText.getText());
                C.setCommunityCity(CommunityCityText.getText());                  
            }
               JOptionPane.showMessageDialog(this, "Community Details Updated");
               
        }
    }//GEN-LAST:event_CommunityUpdateBtnActionPerformed

    private void CommunityIDTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CommunityIDTextKeyReleased
        // TODO add your handling code here:
       String PATTERN = "^[0-9]{0,2}$";
       Pattern patt = Pattern.compile(PATTERN);
       Matcher match = patt.matcher(CommunityIDText.getText());

       if(!match.matches()){            
           JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Value ");
       }
    }//GEN-LAST:event_CommunityIDTextKeyReleased

    private void CommunityNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CommunityNameTextKeyReleased
        // TODO add your handling code here:
       String PATTERN = "^[a-zA-Z]{0,2}$";
       Pattern patt = Pattern.compile(PATTERN);
       Matcher match = patt.matcher(CommunityNameText.getText());

       if(!match.matches()){            
           JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Value ");
       }
    }//GEN-LAST:event_CommunityNameTextKeyReleased

    private void CommunityCityTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CommunityCityTextKeyReleased
        // TODO add your handling code here:
       String PATTERN = "^[a-zA-Z]{0,2}$";
       Pattern patt = Pattern.compile(PATTERN);
       Matcher match = patt.matcher(CommunityCityText.getText());

       if(!match.matches()){            
           JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Value ");
       }
    }//GEN-LAST:event_CommunityCityTextKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CommunityCityText;
    private javax.swing.JTextField CommunityIDText;
    private javax.swing.JTextField CommunityNameText;
    private javax.swing.JButton CommunitySearchBtn;
    private javax.swing.JButton CommunityUpdateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
