/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Doctor;
import model.DoctorHistory;

/**
 *
 * @author parjita
 */
public class UpdateDoctorJList extends javax.swing.JPanel {

    DoctorHistory history;
    /**
     * Creates new form UpdateDoctorJList
     * @param history
     */
    public UpdateDoctorJList(DoctorHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DoctorIdText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DoctorNameText = new javax.swing.JTextField();
        DoctorUpdateBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        HospitalIDText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DoctorContactNumberText = new javax.swing.JTextField();
        DoctorEmailIDText = new javax.swing.JTextField();
        DoctorSerachBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search and UpdateDoctor Detail");

        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("Doctor ID");

        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("Doctor Name");

        DoctorNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorNameTextActionPerformed(evt);
            }
        });

        DoctorUpdateBtn.setBackground(new java.awt.Color(255, 0, 255));
        DoctorUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        DoctorUpdateBtn.setText("Update");
        DoctorUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorUpdateBtnActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 0, 255));
        jLabel4.setText("Hospital ID");

        HospitalIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalIDTextActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 0, 255));
        jLabel5.setText("Contact Number");

        jLabel6.setForeground(new java.awt.Color(255, 0, 255));
        jLabel6.setText("Email ID");

        DoctorContactNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorContactNumberTextActionPerformed(evt);
            }
        });

        DoctorEmailIDText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DoctorEmailIDTextKeyReleased(evt);
            }
        });

        DoctorSerachBtn.setBackground(new java.awt.Color(255, 0, 255));
        DoctorSerachBtn.setForeground(new java.awt.Color(255, 255, 255));
        DoctorSerachBtn.setText("Search");
        DoctorSerachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorSerachBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(DoctorSerachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(136, 136, 136)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(DoctorIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DoctorNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(HospitalIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DoctorContactNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DoctorEmailIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DoctorUpdateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DoctorSerachBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HospitalIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorContactNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorEmailIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(DoctorUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DoctorNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorNameTextActionPerformed

    private void DoctorUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorUpdateBtnActionPerformed
        // TODO add your handling code here:
         for (Doctor D : history.getHistory()){
         
            if(DoctorIdText.getText().equals(String.valueOf(D.getDoctorID()))) {
                
                D.setDoctorName(DoctorNameText.getText());
                D.setHospitalID(Integer.parseInt(HospitalIDText.getText()));  
                D.setDoctorEmailAddress(DoctorEmailIDText.getText());
                D.setDoctorContactNumber(Double.parseDouble(DoctorContactNumberText.getText()));
            }
               JOptionPane.showMessageDialog(this, "Community Details Updated");
               
        }
      

    }//GEN-LAST:event_DoctorUpdateBtnActionPerformed

    private void DoctorContactNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorContactNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorContactNumberTextActionPerformed

    private void HospitalIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalIDTextActionPerformed

    private void DoctorSerachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorSerachBtnActionPerformed
        // TODO add your handling code here:
        int DoctorID = Integer.parseInt(DoctorIdText.getText());
       
       for (Doctor D : history.getHistory()) {
        if (DoctorID == D.getDoctorID()) {
                DoctorNameText.setText(D.getDoctorName());
                HospitalIDText.setText(String.valueOf(D.getHospitalID()));
                DoctorEmailIDText.setText(D.getDoctorEmailAddress());
                DoctorContactNumberText.setText(String.valueOf(D.getDoctorContactNumber()));                
                
                }
       }
                                                     
        // TODO add your handling code here:
     
    }//GEN-LAST:event_DoctorSerachBtnActionPerformed

    private void DoctorIdTextKeyReleased(java.awt.event.KeyEvent evt) {                                         
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(DoctorIdText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid ID ");
        }
    } 
    private void DoctorEmailIDTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DoctorEmailIDTextKeyReleased
        // TODO add your handling code here:
       String PATTERN = "^[a-zA-Z0-9(.+)@(\\\\S+)]{0,40}$";
       Pattern patt = Pattern.compile(PATTERN);
       Matcher match = patt.matcher(DoctorEmailIDText.getText());

       if(!match.matches()){            
           JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid EmailAdress ");
       }
    }//GEN-LAST:event_DoctorEmailIDTextKeyReleased
  private void DoctorContactNumberTextKeyReleased(java.awt.event.KeyEvent evt) {                                                    
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,10}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(DoctorContactNumberText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid PhoneNumber ");
        }
    } 
 private void HospitalIDTextKeyReleased(java.awt.event.KeyEvent evt) {                                           
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(HospitalIDText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid ID ");
        }
    }   
  private void DoctorNameTextKeyReleased(java.awt.event.KeyEvent evt) {                                           
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,40}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(DoctorNameText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Name ");
        }
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DoctorContactNumberText;
    private javax.swing.JTextField DoctorEmailIDText;
    private javax.swing.JTextField DoctorIdText;
    private javax.swing.JTextField DoctorNameText;
    private javax.swing.JButton DoctorSerachBtn;
    private javax.swing.JButton DoctorUpdateBtn;
    private javax.swing.JTextField HospitalIDText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
