/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.DoctorHistory;
import model.Hospital;
import model.HospitalHistory;

/**
 *
 * @author parjita
 */
public class UpdateHospitalJList extends javax.swing.JPanel {

    HospitalHistory history;
    /**
     * Creates new form UpdateHospitalJList
     * @param history
     */
    public UpdateHospitalJList(HospitalHistory history) {
        initComponents();
        this.history = history;
    }

    UpdateHospitalJList(HospitalHistory hospitalHistory, DoctorHistory doctorHistory) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HospitalIdText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        HospitalNameText = new javax.swing.JTextField();
        HospitalUpdateBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        HospitalSearchBtn = new javax.swing.JButton();
        HospitalCityText = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search and Update Hospital Detail");

        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("Hospital ID");

        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("Hospital Name");

        HospitalNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalNameTextActionPerformed(evt);
            }
        });

        HospitalUpdateBtn.setBackground(new java.awt.Color(255, 0, 255));
        HospitalUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        HospitalUpdateBtn.setText("Update");
        HospitalUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalUpdateBtnActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 0, 255));
        jLabel4.setText("City");

        HospitalSearchBtn.setBackground(new java.awt.Color(255, 0, 255));
        HospitalSearchBtn.setForeground(new java.awt.Color(255, 255, 255));
        HospitalSearchBtn.setText("Serach");
        HospitalSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalSearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HospitalSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HospitalIdText, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(HospitalNameText)
                            .addComponent(HospitalUpdateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HospitalCityText))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HospitalIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(HospitalSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HospitalNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HospitalCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(HospitalUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HospitalNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalNameTextActionPerformed

    private void HospitalUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalUpdateBtnActionPerformed
        // TODO add your handling code here:
        for (Hospital H : history.getHistory()){
         
            if(HospitalIdText.getText().equals(String.valueOf(H.getHospitalID()))) {
                
                H.setHospitalName(HospitalNameText.getText());
                H.setHospitalCity(HospitalCityText.getText());                  
            }
               JOptionPane.showMessageDialog(this, "Community Details Updated");
               
        }

       
    }//GEN-LAST:event_HospitalUpdateBtnActionPerformed

    private void HospitalSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalSearchBtnActionPerformed
        // TODO add your handling code here:
        int HospitalID = Integer.parseInt(HospitalIdText.getText());
       
       for (Hospital H : history.getHistory()) {
        if (HospitalID == H.getHospitalID()) {
                HospitalNameText.setText(H.getHospitalName());
                HospitalCityText.setText(H.getHospitalCity());
            }
       }
    }//GEN-LAST:event_HospitalSearchBtnActionPerformed
    private void HospitalNameTextKeyReleased(java.awt.event.KeyEvent evt) {                                             
        // TODO add your handling code here:
         String PATTERN = "^[a-zA-Z]{0,40}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(HospitalNameText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Name ");
        }
    }                                            

    private void HospitalCityTextActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void HospitalCityTextKeyReleased(java.awt.event.KeyEvent evt) {                                             
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,40}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(HospitalCityText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Value ");
        }
    } 
 private void HospitalIdTextKeyReleased(java.awt.event.KeyEvent evt) {                                           
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(HospitalIdText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid ID ");
        }
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HospitalCityText;
    private javax.swing.JTextField HospitalIdText;
    private javax.swing.JTextField HospitalNameText;
    private javax.swing.JButton HospitalSearchBtn;
    private javax.swing.JButton HospitalUpdateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
