/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Patient;
import model.PatientHistory;

/**
 *
 * @author parjita
 */
public class UpdatePatientJList extends javax.swing.JPanel {

    PatientHistory history;
    /**
     * Creates new form UpdatePatientJPanel
     * @param history
     */
    public UpdatePatientJList(PatientHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PatientIdText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PatientNameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PatientGenderText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PatientAddressText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PatientEmailIDText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        PatientPhoneNumberText = new javax.swing.JTextField();
        PatientUpdatebtn = new javax.swing.JButton();
        PatientSearchBtn = new javax.swing.JButton();
        PatientCityText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PatientAgeText = new javax.swing.JTextField();
        PatientHeightText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        PatientWeightText = new javax.swing.JTextField();

        setForeground(new java.awt.Color(255, 0, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search and UpdatePatient Detail");

        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("Patient ID");

        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("Name");

        PatientNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientNameTextActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 0, 255));
        jLabel4.setText("City");

        jLabel6.setForeground(new java.awt.Color(255, 0, 255));
        jLabel6.setText("Gender");

        PatientGenderText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientGenderTextActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 0, 255));
        jLabel8.setText("Address");

        PatientAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientAddressTextActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 0, 255));
        jLabel10.setText("Email ID");

        jLabel11.setForeground(new java.awt.Color(255, 0, 255));
        jLabel11.setText("Phone Number");

        PatientPhoneNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientPhoneNumberTextActionPerformed(evt);
            }
        });

        PatientUpdatebtn.setBackground(new java.awt.Color(255, 0, 255));
        PatientUpdatebtn.setForeground(new java.awt.Color(255, 255, 255));
        PatientUpdatebtn.setText("Update");
        PatientUpdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientUpdatebtnActionPerformed(evt);
            }
        });

        PatientSearchBtn.setBackground(new java.awt.Color(255, 0, 255));
        PatientSearchBtn.setForeground(new java.awt.Color(255, 255, 255));
        PatientSearchBtn.setText("Search");
        PatientSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientSearchBtnActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 0, 255));
        jLabel12.setText("Age");

        jLabel13.setForeground(new java.awt.Color(255, 0, 255));
        jLabel13.setText("Height");

        jLabel14.setForeground(new java.awt.Color(255, 0, 255));
        jLabel14.setText("Weight");

        PatientWeightText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientWeightTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PatientSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PatientIdText, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(PatientNameText)
                                    .addComponent(PatientGenderText)
                                    .addComponent(PatientAddressText)
                                    .addComponent(PatientEmailIDText)
                                    .addComponent(PatientPhoneNumberText)
                                    .addComponent(PatientUpdatebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PatientCityText)
                                    .addComponent(PatientAgeText)
                                    .addComponent(PatientHeightText)
                                    .addComponent(PatientWeightText)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PatientSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientHeightText, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientWeightText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(PatientGenderText, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientEmailIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientPhoneNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(PatientUpdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PatientNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientNameTextActionPerformed

    private void PatientGenderTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientGenderTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientGenderTextActionPerformed

    private void PatientAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientAddressTextActionPerformed

    private void PatientUpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientUpdatebtnActionPerformed
        // TODO add your handling code here:
      for (Patient D : history.getHistory()){
         
            if(PatientIdText.getText().equals(String.valueOf(D.getPatientID()))) {
                
                D.setPatientName(PatientNameText.getText()); 
                
                D.setPatientGender(PatientGenderText.getText()); 
                D.setPatientAge(Integer.parseInt(PatientAgeText.getText()));
                D.setPatientHeight(Integer.parseInt(PatientHeightText.getText()));
                D.setPatientWeight(Integer.parseInt(PatientWeightText.getText()));
                
                D.setPatientCity(PatientCityText.getText()); 
                D.setPatientAddress(PatientAddressText.getText());                 
                            
                D.setPatientEmail(PatientEmailIDText.getText());
                D.setPatientPhoneNumber(Double.parseDouble(PatientPhoneNumberText.getText()));
            }
               JOptionPane.showMessageDialog(this, "Community Details Updated");
               
        }
        

    }//GEN-LAST:event_PatientUpdatebtnActionPerformed

    private void PatientSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientSearchBtnActionPerformed
        // TODO add your handling code here:
           int PatientID = Integer.parseInt(PatientIdText.getText());
       
       for (Patient P : history.getHistory()) {
        if (PatientID == P.getPatientID()) {
                PatientNameText.setText(P.getPatientName());
                
                PatientGenderText.setText(P.getPatientGender());
                PatientAgeText.setText(String.valueOf(P.getPatientAge()));
                PatientWeightText.setText(String.valueOf(P.getPatientWeight()));
                PatientHeightText.setText(String.valueOf(P.getPatientHeight()));
                
                PatientCityText.setText(P.getPatientCity());
                PatientAddressText.setText(P.getPatientAddress());
                        
                PatientEmailIDText.setText(P.getPatientEmail());
                PatientPhoneNumberText.setText(String.valueOf(P.getPatientPhoneNumber()));                
                
                }
       }
    }//GEN-LAST:event_PatientSearchBtnActionPerformed

    private void PatientWeightTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientWeightTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientWeightTextActionPerformed

    private void PatientPhoneNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientPhoneNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientPhoneNumberTextActionPerformed

 private void PatientIdTextKeyReleased(java.awt.event.KeyEvent evt) {                                          
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(PatientIdText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid ID ");
        }
    }                                         

    private void PatientNameTextKeyReleased(java.awt.event.KeyEvent evt) {                                            
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,40}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(PatientNameText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Name ");
        }
    }                                           

    private void PatientAgeTextKeyReleased(java.awt.event.KeyEvent evt) {                                           
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,2}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(PatientAgeText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Value ");
        }
    }                                          

    private void PatientPhoneNumberTextKeyReleased(java.awt.event.KeyEvent evt) {                                                   
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,9}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(PatientPhoneNumberText.getText());
        
        if(!match.matches()){            
            JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid Value ");
        }
    }                                                  

    private void PatientEmailIDTextKeyReleased(java.awt.event.KeyEvent evt) {                                               
        // TODO add your handling code here:
       String PATTERN = "^[a-zA-Z0-9(.+)@(\\\\S+)]{0,40}$";
       Pattern patt = Pattern.compile(PATTERN);
       Matcher match = patt.matcher(PatientEmailIDText.getText());

       if(!match.matches()){            
           JOptionPane.showMessageDialog(this,"Invalid ! Please Enter Valid EmailAdress ");
       }
    }           
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PatientAddressText;
    private javax.swing.JTextField PatientAgeText;
    private javax.swing.JTextField PatientCityText;
    private javax.swing.JTextField PatientEmailIDText;
    private javax.swing.JTextField PatientGenderText;
    private javax.swing.JTextField PatientHeightText;
    private javax.swing.JTextField PatientIdText;
    private javax.swing.JTextField PatientNameText;
    private javax.swing.JTextField PatientPhoneNumberText;
    private javax.swing.JButton PatientSearchBtn;
    private javax.swing.JButton PatientUpdatebtn;
    private javax.swing.JTextField PatientWeightText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
