/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Vitals;
import model.VitalsHistory;

/**
 *
 * @author parjita
 */
public class ViewVitalsJList extends javax.swing.JPanel {

    VitalsHistory history;
    /**
     * Creates new form ViewVitalsJList
     * @param history
     */
    public ViewVitalsJList(VitalsHistory history) {
        initComponents();
        this.history = history;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        VitalsTable = new javax.swing.JTable();
        VitalsDeleteBtn = new javax.swing.JButton();

        VitalsTable.setBackground(new java.awt.Color(255, 0, 255));
        VitalsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Blood Pressure", "Heart Rate", "Body Temperature"
            }
        ));
        jScrollPane1.setViewportView(VitalsTable);

        VitalsDeleteBtn.setBackground(new java.awt.Color(255, 0, 255));
        VitalsDeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        VitalsDeleteBtn.setText("Delete");
        VitalsDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VitalsDeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VitalsDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VitalsDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VitalsDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VitalsDeleteBtnActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex = VitalsTable.getSelectedRow();
       
       if (selectedRowIndex<0){           
           JOptionPane.showMessageDialog(this, "Please select a row to delete.");
           return;
       }
       
       DefaultTableModel model = (DefaultTableModel) VitalsTable.getModel();
       Vitals selectedCommunity = (Vitals) model.getValueAt(selectedRowIndex,0);
       history.deleteVitals(selectedCommunity);
       JOptionPane.showMessageDialog(this, "Community signs delete.");
       
       populateTable();
    }//GEN-LAST:event_VitalsDeleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VitalsDeleteBtn;
    private javax.swing.JTable VitalsTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
           DefaultTableModel model = (DefaultTableModel) VitalsTable.getModel();
            model.setRowCount(0);

            for (Vitals V : history.getHistory()){

                   Object[] row = new Object[3];
                   row[0] = V;
                   row[1] = V.getHeartRate();
                   row[2] = V.getBodyTemperature();
                   
                   model.addRow(row);
                 
            } 
    }

}
