/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import UI.ViewVitalsJList;
import UI.CreateVitalsJForm;
import UI.SystemAdmin;
import javax.swing.JFrame;
import model.VitalsHistory;

/**
 *
 * @author parjita
 */
public class VitalsFrame extends javax.swing.JFrame {

     VitalsHistory history;
    /**
     * Creates new form VitalsFrame
     */
    public VitalsFrame() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.history = new VitalsHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        CommunityLeftPanel = new javax.swing.JPanel();
        CreateCommunityList = new javax.swing.JButton();
        ViewCommunityList = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        CommunityRightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CommunityLeftPanel.setPreferredSize(new java.awt.Dimension(32767, 32767));

        CreateCommunityList.setBackground(new java.awt.Color(255, 0, 255));
        CreateCommunityList.setForeground(new java.awt.Color(255, 255, 255));
        CreateCommunityList.setText("Create");
        CreateCommunityList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateCommunityListActionPerformed(evt);
            }
        });

        ViewCommunityList.setBackground(new java.awt.Color(255, 0, 255));
        ViewCommunityList.setForeground(new java.awt.Color(255, 255, 255));
        ViewCommunityList.setText("View");
        ViewCommunityList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCommunityListActionPerformed(evt);
            }
        });

        BackBtn.setBackground(new java.awt.Color(255, 0, 255));
        BackBtn.setForeground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CommunityLeftPanelLayout = new javax.swing.GroupLayout(CommunityLeftPanel);
        CommunityLeftPanel.setLayout(CommunityLeftPanelLayout);
        CommunityLeftPanelLayout.setHorizontalGroup(
            CommunityLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommunityLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CommunityLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(CreateCommunityList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewCommunityList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CommunityLeftPanelLayout.setVerticalGroup(
            CommunityLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommunityLeftPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(CreateCommunityList, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ViewCommunityList, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(CommunityLeftPanel);

        CommunityRightPanel.setPreferredSize(new java.awt.Dimension(32767, 32767));

        javax.swing.GroupLayout CommunityRightPanelLayout = new javax.swing.GroupLayout(CommunityRightPanel);
        CommunityRightPanel.setLayout(CommunityRightPanelLayout);
        CommunityRightPanelLayout.setHorizontalGroup(
            CommunityRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        CommunityRightPanelLayout.setVerticalGroup(
            CommunityRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(CommunityRightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateCommunityListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateCommunityListActionPerformed

        // TODO add your handling code here:
        CreateVitalsJForm CreatePanel = new CreateVitalsJForm(history);
        jSplitPane1.setRightComponent(CreatePanel);
    }//GEN-LAST:event_CreateCommunityListActionPerformed

    private void ViewCommunityListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCommunityListActionPerformed
        // TODO add your handling code here:
        ViewVitalsJList ViewPanel = new ViewVitalsJList(history);
        jSplitPane1.setRightComponent(ViewPanel);
    }//GEN-LAST:event_ViewCommunityListActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        SystemAdmin frame = new SystemAdmin();
        frame.setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VitalsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VitalsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VitalsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VitalsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VitalsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JPanel CommunityLeftPanel;
    private javax.swing.JPanel CommunityRightPanel;
    private javax.swing.JButton CreateCommunityList;
    private javax.swing.JButton ViewCommunityList;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
